# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20171025_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friends',
            new_name='users',
        ),
    ]
